"""Cain CLI entry point.

Commands:
  run    Initialize workspace + scope and drive the orchestrator pipeline.
  --version  Print version and exit.

Security: ``run --target`` on a public host without ``--i-have-authorization``
is rejected before anything starts. Credentials are never printed.

经典 Route A:``run`` 注入三阶段真实 handler——recon/test 共享发现 executor,
report 走独立校验 session 的 FindingsPipeline(发现≠校验,§3.3 防自证);
技能经仓库 SkillLoader 按阶段加载,缺失自动降级为无技能 prompt。
"""

from __future__ import annotations

import argparse
import ipaddress
import sys
from typing import Any

from cain_agent import __version__
from cain_agent.orchestrator import Orchestrator, StageHandler
from cain_agent.workspace import SCOPE_FILE, Workspace

__all__ = ["main", "build_parser", "is_local_target"]

# Default tool whitelist: Bash only for Phase 1 (DESIGN §3.2: minimal surface).
# Read/Write land later once ScopeGuard local-exemption is settled.
DEFAULT_ALLOWED_TOOLS: list[str] = ["Bash"]

# Targets that don't need explicit authorization confirmation.
_LOCAL_SUFFIXES = (".local", ".localhost")
_LOCAL_HOSTNAMES = frozenset({"localhost", "ip6-localhost"})
_LOOPBACK_IPS = frozenset({"127.0.0.1", "::1"})

# Exit codes
EXIT_OK = 0
EXIT_ARG_ERROR = 2


def is_local_target(target: str) -> bool:
    """True if *target* is loopback / localhost / .local — no auth confirmation needed."""
    target = target.strip().lower()
    # Strip URL scheme (http://, https://) and any path so that
    # "http://127.0.0.1:8080" is judged the same as "127.0.0.1:8080".
    if "://" in target:
        target = target.split("://", 1)[1]
    target = target.split("/", 1)[0]
    # Pure IP (v4 or v6, e.g. "::1") — judge directly, never port-strip.
    try:
        ip = ipaddress.ip_address(target)
        return ip.is_private or ip.is_loopback or ip.is_link_local
    except ValueError:
        pass
    # Not a bare IP: strip a trailing port so hostname/suffix/IP checks see the
    # bare host (e.g. "localhost:3000" -> "localhost", "[::1]:8080" -> "[::1]").
    host = target.rsplit(":", 1)[0] if ":" in target else target
    host = host.strip("[]")
    if host in _LOCAL_HOSTNAMES or host in _LOOPBACK_IPS:
        return True
    if any(host.endswith(suffix) for suffix in _LOCAL_SUFFIXES):
        return True
    # Private / link-local / loopback IP ranges (host[:port] form)
    try:
        ip = ipaddress.ip_address(host)
        return ip.is_private or ip.is_loopback or ip.is_link_local
    except ValueError:
        pass
    return False


def _write_scope_yaml(workspace: Workspace, target: str) -> None:
    """Write a scope.yaml with *target* as the sole in_scope entry."""
    scope_path = workspace.path(SCOPE_FILE)
    content = (
        "# scope.yaml — generated by `cain-agent run`\n"
        f"# Target: {target}\n"
        "# ⚠️  仅限对【自有资产】或【已获得书面授权】的目标进行测试。\n\n"
        "in_scope:\n"
        f"  - {target}\n"
        "out_of_scope: []\n"
    )
    scope_path.write_text(content, encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    """Construct the top-level argument parser with subcommands."""
    parser = argparse.ArgumentParser(
        prog="cain-agent",
        description="Cain — Real-world AI Penetration Testing Engineer (authorized use only)",
    )
    parser.add_argument("--version", action="store_true", help="print version and exit")

    sub = parser.add_subparsers(dest="command")

    run = sub.add_parser("run", help="initialize workspace and run the orchestrator pipeline")
    run.add_argument(
        "--target",
        required=True,
        help="target host/IP to test (written to scope.yaml in_scope)",
    )
    run.add_argument(
        "--workspace",
        default="./workspace",
        help="workspace directory (default: ./workspace)",
    )
    run.add_argument(
        "--idle-timeout",
        type=float,
        default=300.0,
        help="idle timeout in seconds (default: 300)",
    )
    run.add_argument(
        "--total-budget",
        type=float,
        default=None,
        help="total wall-clock budget in seconds (default: unlimited)",
    )
    run.add_argument(
        "--dry-run",
        action="store_true",
        help="initialize workspace + scope and print execution plan, don't start Agent",
    )
    run.add_argument(
        "--i-have-authorization",
        action="store_true",
        dest="i_have_authorization",
        help="confirm you have written authorization for the target (required for public targets)",
    )

    return parser


def _build_executor(args: argparse.Namespace) -> Any:
    """Construct the discovery SDKExecutor for a run.

    Kept as a standalone function so tests can monkeypatch it to avoid real
    Agent starts (zero token spend).
    """
    from cain_agent.executor import SDKExecutor

    return SDKExecutor(
        allowed_tools=DEFAULT_ALLOWED_TOOLS,
        idle_timeout=args.idle_timeout,
        total_budget=args.total_budget,
    )


def _build_validation_executor(args: argparse.Namespace) -> Any:
    """Construct the validation SDKExecutor — a distinct session from discovery.

    只读校验通道:零工具白名单(SDKExecutor 默认),校验 Agent 只输出结构化
    JSON,不执行任何验证性操作。与 ``_build_executor`` 分开构造,保证
    FindingsPipeline 的「发现者≠校验者」约束在结构上成立;分开成函数也便于
    测试独立 monkeypatch(零真实 Agent 启动)。
    """
    from cain_agent.executor import SDKExecutor

    return SDKExecutor(
        allowed_tools=[],  # 只读校验通道:默认零工具
        idle_timeout=args.idle_timeout,
        total_budget=args.total_budget,
    )


def _build_handlers(
    executor: Any,
    validation_executor: Any,
    workspace: Workspace,
) -> dict[str, StageHandler]:
    """构造经典 Route A 的三阶段真实 handler,供 Orchestrator 注入。

    - recon / test 共享「发现 executor」;report 经 ``make_report_handler``
      驱动 FindingsPipeline,校验走独立 session——发现与校验永不共享 session。
    - 技能加载用仓库 SkillLoader + 默认 ``skills/`` 根(既有约定),阶段零技能
      命中自动降级为无技能 prompt,不炸。
    - 独立函数便于测试逐件 monkeypatch / spy,零真实 Agent 启动。
    """
    from cain_agent.handlers import SkillLoader, make_recon_handler, make_test_handler
    from cain_agent.pipeline import FindingsPipeline, make_report_handler

    skill_loader = SkillLoader()  # 仓库 skills/ 根,既有约定
    recon_handler = make_recon_handler(executor, skill_loader)
    test_handler = make_test_handler(executor, skill_loader)
    pipeline = FindingsPipeline(
        workspace,
        discovery_executor=executor,
        validation_executor=validation_executor,
    )
    report_handler = make_report_handler(pipeline)
    return {
        "recon": recon_handler,
        "test": test_handler,
        "report": report_handler,
    }


def cmd_run(args: argparse.Namespace, stdout: Any | None = None) -> int:
    """Execute the ``run`` subcommand."""
    if stdout is None:
        stdout = sys.stdout
    target = args.target.strip()
    if not target:
        print("错误: --target 不能为空", file=sys.stderr)
        return EXIT_ARG_ERROR

    # Authorization gate: public targets require explicit confirmation.
    if not is_local_target(target) and not args.i_have_authorization:
        print(
            f"⚠️  目标 {target!r} 不是本地/私网地址。\n"
            "    对公网目标执行测试需要书面授权。\n"
            "    如果你已获得授权,请加 --i-have-authorization 标志重新运行。\n"
            "    授权声明将被记录在 workspace 执行历史中。",
            file=sys.stderr,
        )
        return EXIT_ARG_ERROR

    # Initialize workspace + scope.
    try:
        workspace = Workspace(args.workspace)
    except Exception as exc:
        print(f"错误: workspace 初始化失败: {exc}", file=sys.stderr)
        return EXIT_ARG_ERROR

    _write_scope_yaml(workspace, target)

    if args.dry_run:
        print("Cain dry-run — 执行计划", file=stdout)
        print(f"  目标:     {target}", file=stdout)
        print(f"  工作区:   {workspace.root.resolve()}", file=stdout)
        print(f"  授权范围: {workspace.path(SCOPE_FILE).resolve()}", file=stdout)
        print("  阶段:     recon → test → report", file=stdout)
        print(f"  工具白名单: {DEFAULT_ALLOWED_TOOLS}", file=stdout)
        if args.i_have_authorization:
            print("  授权确认: ✅ 已声明授权", file=stdout)
        print("\n  (dry-run: 不启动 Agent)", file=stdout)
        return EXIT_OK

    # Build executors, real handlers, then run the orchestrator pipeline.
    try:
        executor = _build_executor(args)
    except Exception as exc:
        print(f"错误: executor 构造失败: {exc}", file=sys.stderr)
        return EXIT_ARG_ERROR

    try:
        validation_executor = _build_validation_executor(args)
    except Exception as exc:
        print(f"错误: 校验 executor 构造失败: {exc}", file=sys.stderr)
        return EXIT_ARG_ERROR

    try:
        handlers = _build_handlers(executor, validation_executor, workspace)
    except Exception as exc:
        print(f"错误: handler 构造失败: {exc}", file=sys.stderr)
        return EXIT_ARG_ERROR

    # 构造与执行分开兜底:构造失败在 orchestrator 赋值前返回,绝不引用未绑定局部变量。
    try:
        orchestrator = Orchestrator(executor, workspace, handlers=handlers)
    except Exception as exc:
        print(f"错误: orchestrator 构造失败: {exc}", file=sys.stderr)
        return EXIT_ARG_ERROR

    try:
        final_state = orchestrator.run()
    except KeyboardInterrupt:
        print("\n中断: 用户取消 (partial results in workspace)", file=sys.stderr)
        return EXIT_OK
    except Exception as exc:
        # Budget/timeout interruptions produce partial results.
        print(f"\n中断: {exc} (partial results in workspace)", file=sys.stderr)
        final_state = orchestrator.load_state()

    # Summary: stage artifact paths.
    print("\nCain run 完成\n", file=stdout)
    history = final_state.get("history", [])
    for entry in history:
        stage = entry.get("stage", "?")
        artifacts = entry.get("artifacts", [])
        print(f"  [{stage}] {entry.get('summary', '')}", file=stdout)
        for art in artifacts:
            print(f"    → {workspace.root / art}", file=stdout)
    return EXIT_OK


def main() -> None:
    """CLI entry point (called by ``cain-agent`` script or ``python -m``)."""
    parser = build_parser()
    args = parser.parse_args()

    if args.version:
        print(f"cain-agent {__version__}")
        return

    if args.command == "run":
        code = cmd_run(args)
        if code:
            sys.exit(code)
        return

    # No subcommand: print help.
    parser.print_help()


if __name__ == "__main__":
    main()
