"""Cain CLI entry point.

Commands:
  run    Initialize workspace + scope and drive the orchestrator pipeline.
  --version  Print version and exit.

Security: ``run --target`` on a public host without ``--i-have-authorization``
is rejected before anything starts. Credentials are never printed.
"""

from __future__ import annotations

import argparse
import ipaddress
import sys
from typing import Any

from cain_agent import __version__
from cain_agent.orchestrator import Orchestrator
from cain_agent.workspace import SCOPE_FILE, Workspace

__all__ = ["main", "build_parser", "is_local_target"]

# Default tool whitelist: Bash only for Phase 1 (DESIGN §3.2: minimal surface).
# Read/Write land later once ScopeGuard local-exemption is settled.
DEFAULT_ALLOWED_TOOLS: list[str] = ["Bash"]

# Targets that don't need explicit authorization confirmation.
_LOCAL_SUFFIXES = (".local", ".localhost")
_LOCAL_HOSTNAMES = frozenset({"localhost", "ip6-localhost"})
_LOOPBACK_IPS = frozenset({"127.0.0.1", "::1"})

# Exit codes
EXIT_OK = 0
EXIT_ARG_ERROR = 2


def is_local_target(target: str) -> bool:
    """True if *target* is loopback / localhost / .local — no auth confirmation needed."""
    target = target.strip().lower()
    if target in _LOCAL_HOSTNAMES or target in _LOOPBACK_IPS:
        return True
    if any(target.endswith(suffix) for suffix in _LOCAL_SUFFIXES):
        return True
    # Private / link-local / loopback IP ranges
    try:
        ip = ipaddress.ip_address(target)
        return ip.is_private or ip.is_loopback or ip.is_link_local
    except ValueError:
        pass
    # Strip port if present for IP check
    if ":" in target:
        host = target.rsplit(":", 1)[0]
        try:
            ip = ipaddress.ip_address(host)
            return ip.is_private or ip.is_loopback or ip.is_link_local
        except ValueError:
            pass
    return False


def _write_scope_yaml(workspace: Workspace, target: str) -> None:
    """Write a scope.yaml with *target* as the sole in_scope entry."""
    scope_path = workspace.path(SCOPE_FILE)
    content = (
        "# scope.yaml — generated by `cain-agent run`\n"
        f"# Target: {target}\n"
        "# ⚠️  仅限对【自有资产】或【已获得书面授权】的目标进行测试。\n\n"
        "in_scope:\n"
        f"  - {target}\n"
        "out_of_scope: []\n"
    )
    scope_path.write_text(content, encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    """Construct the top-level argument parser with subcommands."""
    parser = argparse.ArgumentParser(
        prog="cain-agent",
        description="Cain — Real-world AI Penetration Testing Engineer (authorized use only)",
    )
    parser.add_argument("--version", action="store_true", help="print version and exit")

    sub = parser.add_subparsers(dest="command")

    run = sub.add_parser("run", help="initialize workspace and run the orchestrator pipeline")
    run.add_argument(
        "--target",
        required=True,
        help="target host/IP to test (written to scope.yaml in_scope)",
    )
    run.add_argument(
        "--workspace",
        default="./workspace",
        help="workspace directory (default: ./workspace)",
    )
    run.add_argument(
        "--idle-timeout",
        type=float,
        default=300.0,
        help="idle timeout in seconds (default: 300)",
    )
    run.add_argument(
        "--total-budget",
        type=float,
        default=None,
        help="total wall-clock budget in seconds (default: unlimited)",
    )
    run.add_argument(
        "--dry-run",
        action="store_true",
        help="initialize workspace + scope and print execution plan, don't start Agent",
    )
    run.add_argument(
        "--i-have-authorization",
        action="store_true",
        dest="i_have_authorization",
        help="confirm you have written authorization for the target (required for public targets)",
    )

    return parser


def _build_executor(args: argparse.Namespace) -> Any:
    """Construct the SDKExecutor for a run.

    Kept as a standalone function so tests can monkeypatch it to avoid real
    Agent starts (zero token spend).
    """
    from cain_agent.executor import SDKExecutor

    return SDKExecutor(
        allowed_tools=DEFAULT_ALLOWED_TOOLS,
        idle_timeout=args.idle_timeout,
        total_budget=args.total_budget,
    )


def cmd_run(args: argparse.Namespace, stdout: Any | None = None) -> int:
    """Execute the ``run`` subcommand."""
    if stdout is None:
        stdout = sys.stdout
    target = args.target.strip()
    if not target:
        print("错误: --target 不能为空", file=sys.stderr)
        return EXIT_ARG_ERROR

    # Authorization gate: public targets require explicit confirmation.
    if not is_local_target(target) and not args.i_have_authorization:
        print(
            f"⚠️  目标 {target!r} 不是本地/私网地址。\n"
            "    对公网目标执行测试需要书面授权。\n"
            "    如果你已获得授权,请加 --i-have-authorization 标志重新运行。\n"
            "    授权声明将被记录在 workspace 执行历史中。",
            file=sys.stderr,
        )
        return EXIT_ARG_ERROR

    # Initialize workspace + scope.
    try:
        workspace = Workspace(args.workspace)
    except Exception as exc:
        print(f"错误: workspace 初始化失败: {exc}", file=sys.stderr)
        return EXIT_ARG_ERROR

    _write_scope_yaml(workspace, target)

    if args.dry_run:
        print("Cain dry-run — 执行计划", file=stdout)
        print(f"  目标:     {target}", file=stdout)
        print(f"  工作区:   {workspace.root.resolve()}", file=stdout)
        print(f"  授权范围: {workspace.path(SCOPE_FILE).resolve()}", file=stdout)
        print("  阶段:     recon → test → report", file=stdout)
        print(f"  工具白名单: {DEFAULT_ALLOWED_TOOLS}", file=stdout)
        if args.i_have_authorization:
            print("  授权确认: ✅ 已声明授权", file=stdout)
        print("\n  (dry-run: 不启动 Agent)", file=stdout)
        return EXIT_OK

    # Build executor and run orchestrator pipeline.
    try:
        executor = _build_executor(args)
    except Exception as exc:
        print(f"错误: executor 构造失败: {exc}", file=sys.stderr)
        return EXIT_ARG_ERROR

    try:
        orchestrator = Orchestrator(executor, workspace)
        final_state = orchestrator.run()
    except KeyboardInterrupt:
        print("\n中断: 用户取消 (partial results in workspace)", file=sys.stderr)
        return EXIT_OK
    except Exception as exc:
        # Budget/timeout interruptions produce partial results.
        print(f"\n中断: {exc} (partial results in workspace)", file=sys.stderr)
        final_state = getattr(orchestrator, "load_state", lambda: {})()

    # Summary: stage artifact paths.
    print("\nCain run 完成\n", file=stdout)
    history = final_state.get("history", [])
    for entry in history:
        stage = entry.get("stage", "?")
        artifacts = entry.get("artifacts", [])
        print(f"  [{stage}] {entry.get('summary', '')}", file=stdout)
        for art in artifacts:
            print(f"    → {workspace.root / art}", file=stdout)
    return EXIT_OK


def main() -> None:
    """CLI entry point (called by ``cain-agent`` script or ``python -m``)."""
    parser = build_parser()
    args = parser.parse_args()

    if args.version:
        print(f"cain-agent {__version__}")
        return

    if args.command == "run":
        code = cmd_run(args)
        if code:
            sys.exit(code)
        return

    # No subcommand: print help.
    parser.print_help()


if __name__ == "__main__":
    main()
